name: lumi_tools
channels:
  - defaults
dependencies:
  - numpy=1.16.3
  - numpy-base=1.16.3
  - numpydoc=0.9.1
  - pandas=0.24.2
  - patsy=0.5.1
  - pip=19.1.1
  - python=3.6.8
  - scipy=1.2.1
  - seaborn=0.9.0
  - statsmodels=0.10.0
  - tornado=6.0.2